// Generates typed ABI exports from compiled Hardhat artifacts so the published
// ABIs can never drift from the Solidity sources. Run as part of `build`.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Contracts whose ABIs are published from this package. */
const contracts = [{ name: "Counter", exportName: "counterAbi" }];

let out =
  "// AUTO-GENERATED by scripts/generate-abi.mjs — do not edit.\n" +
  "// Run `pnpm --filter @arbiter/contracts build` to regenerate.\n\n";

for (const { name, exportName } of contracts) {
  const artifactPath = join(
    root,
    `artifacts/contracts/${name}.sol/${name}.json`,
  );
  const { abi } = JSON.parse(readFileSync(artifactPath, "utf8"));
  out += `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(join(root, "src/generated/abi.ts"), out);
console.log(`Generated src/generated/abi.ts (${contracts.length} contract(s))`);
